default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
    - id: mypy
