# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  test:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/Spectacles

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements-dev.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install spectacles
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            pip install .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: mypy
          command: |
            . venv/bin/activate
            mypy spectacles

      - run:
          name: flake8
          command: |
            . venv/bin/activate
            flake8 spectacles tests

      - run:
          name: black
          command: |
            . venv/bin/activate
            black --check spectacles tests

      - run:
          name: pytest
          command: |
            . venv/bin/activate
            python -m pytest

      - run:
          name: coverage
          command: |
            . venv/bin/activate
            coverage run --source spectacles -m pytest
            coverage report
            coverage html
            coverage xml

      - store_artifacts:
          path: htmlcov

      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2
  test:
    jobs:
      - test
